version: "3.9"
services:
  server:
    build: .
    ports:
      - "80:8080"
    restart: "always"
    volumes:
      - type: bind
        source: ./logs
        target: /usr/src/app/logs
  db:
    image: "influxdb:2.6-alpine"
    volumes:
      - ./db:/var/lib/influxdb2:rw
    ports:
      - "2230:8086"
    restart: "always"

